# Generated by Django 3.2.8 on 2021-10-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'managed': False, 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='produtoscompra',
            options={'managed': False, 'verbose_name': 'Produto_Compra', 'verbose_name_plural': 'Produtos_Compras'},
        ),
        migrations.AlterModelOptions(
            name='receitasmedicas',
            options={'managed': False, 'verbose_name': 'receita médica', 'verbose_name_plural': 'receitas médicas'},
        ),
        migrations.AlterModelOptions(
            name='tiposprodutos',
            options={'managed': False, 'verbose_name': 'Tipo Produto', 'verbose_name_plural': 'Tipos Produtos'},
        ),
    ]
